version: "3.7"
services:
  app:
    build:
      args:
        user: Ridoy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: node-mongo
    container_name: node-mongo-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./:/var/www:cached
    links:
      - mongo
    networks:
      - node-mongo-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: node-mongo
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - node-mongo-network
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    networks:
      - node-mongo-network
networks:
  node-mongo-network:
    driver: bridge